//! Spec 06 §5 — `.xlsx` export of the Spec 05 reports. `rust_xlsxwriter` was
//! added to `Cargo.toml` alongside `calamine` for Spec 06 but sat unused
//! until this module: every export shares one sheet layout so a dozen report
//! shapes don't turn into a dozen copy-pasted formatting passes.
//!
//! Every sheet gets, in order: a banner row (Decision #6 — exports are
//! readable copies, not import formats; the banner text is exactly what
//! importers check for and reject on, so it must never drift from theirs),
//! a header block (company name, report title, period, generation
//! timestamp), a frozen + auto-filtered header row, and typed columns —
//! dates as real Excel dates, money as `₦#,##0.00` numbers, never text
//! (Spec 06 §5's own wording: "what you see on screen is what lands in the
//! file", but as data, not a picture of it).

use crate::reports::{
    AgingRow, BalanceSheet, CashBasisSummary, CashFlowStatement, GeneralLedger, IncomeStatement,
    SalesRow, TrialBalanceRow, VatReport, WhtCreditLine, WhtRemittanceLine, ContactStatement,
};
use rust_xlsxwriter::{ExcelDateTime, Format, FormatBorder, Workbook, Worksheet, XlsxError};

/// Importers reject any file bearing this text (Spec 06 §5.4 Decision #6) —
/// keep it byte-for-byte identical wherever an importer might check for it.
pub const REIMPORT_BANNER: &str =
    "Generated by LedgerOne — for reading and analysis; re-importing this file is not supported.";

pub struct ExportHeader<'a> {
    pub company_name: &'a str,
    pub report_title: &'a str,
    pub period_label: &'a str,
    pub generated_at: &'a str, // ISO datetime, e.g. "2026-07-18T14:03:00"
}

#[derive(Debug, Clone)]
enum Cell {
    Text(String),
    Kobo(i64),
    Qty(f64),
    Date(String), // ISO date
}

fn t(s: impl Into<String>) -> Cell {
    Cell::Text(s.into())
}

fn to_xlsx_err(e: XlsxError) -> String {
    e.to_string()
}

fn build(header: &ExportHeader, columns: &[&str], rows: &[Vec<Cell>]) -> Result<Vec<u8>, String> {
    let mut wb = Workbook::new();
    let sheet = wb.add_worksheet();
    write_sheet(sheet, header, columns, rows).map_err(to_xlsx_err)?;
    wb.save_to_buffer().map_err(to_xlsx_err)
}

fn write_sheet(
    sheet: &mut Worksheet, header: &ExportHeader, columns: &[&str], rows: &[Vec<Cell>],
) -> Result<(), XlsxError> {
    let italic = Format::new().set_italic();
    let bold = Format::new().set_bold();
    let money_fmt = Format::new().set_num_format("₦#,##0.00");
    let date_fmt = Format::new().set_num_format("dd/mm/yyyy");
    let header_fmt = Format::new().set_bold().set_border(FormatBorder::Thin);

    let last_col = (columns.len().max(2) - 1) as u16;
    sheet.merge_range(0, 0, 0, last_col, REIMPORT_BANNER, &italic)?;
    sheet.write_string_with_format(1, 0, header.company_name, &bold)?;
    sheet.write_string(2, 0, header.report_title)?;
    sheet.write_string(3, 0, header.period_label)?;
    sheet.write_string(4, 0, format!("Generated {}", header.generated_at))?;

    let header_row = 6u32;
    for (i, name) in columns.iter().enumerate() {
        sheet.write_string_with_format(header_row, i as u16, *name, &header_fmt)?;
    }
    sheet.set_freeze_panes(header_row + 1, 0)?;

    for (r, row) in rows.iter().enumerate() {
        let row_idx = header_row + 1 + r as u32;
        for (c, cell) in row.iter().enumerate() {
            let col_idx = c as u16;
            match cell {
                Cell::Text(s) => sheet.write_string(row_idx, col_idx, s)?,
                Cell::Kobo(k) => sheet.write_number_with_format(row_idx, col_idx, *k as f64 / 100.0, &money_fmt)?,
                Cell::Qty(q) => sheet.write_number(row_idx, col_idx, *q)?,
                Cell::Date(d) => {
                    let dt = ExcelDateTime::parse_from_str(d)?;
                    sheet.write_datetime_with_format(row_idx, col_idx, &dt, &date_fmt)?
                }
            };
        }
        for c in 0..columns.len() {
            sheet.set_column_width(c as u16, 20)?;
        }
    }
    let last_row = if rows.is_empty() { header_row } else { header_row + rows.len() as u32 };
    sheet.autofilter(header_row, 0, last_row, last_col)?;
    Ok(())
}

pub fn export_aging(header: &ExportHeader, rows: &[AgingRow]) -> Result<Vec<u8>, String> {
    let columns = ["Contact", "Current", "1-30 days", "31-60 days", "61-90 days", "90+ days", "Total owed", "Deposits held"];
    let data = rows
        .iter()
        .map(|r| {
            vec![
                t(&r.contact_name), Cell::Kobo(r.buckets.current_kobo), Cell::Kobo(r.buckets.d1_30_kobo),
                Cell::Kobo(r.buckets.d31_60_kobo), Cell::Kobo(r.buckets.d61_90_kobo), Cell::Kobo(r.buckets.d90_plus_kobo),
                Cell::Kobo(r.buckets.total()), Cell::Kobo(r.deposit_kobo),
            ]
        })
        .collect::<Vec<_>>();
    build(header, &columns, &data)
}

pub fn export_sales(header: &ExportHeader, rows: &[SalesRow]) -> Result<Vec<u8>, String> {
    let columns = ["Name", "Quantity", "Net sales (ex-VAT)"];
    let data = rows
        .iter()
        .map(|r| vec![t(&r.label), Cell::Qty(r.qty_milli as f64 / 1000.0), Cell::Kobo(r.value_kobo)])
        .collect::<Vec<_>>();
    build(header, &columns, &data)
}

fn account_amount_rows(rows: &crate::reports::AccountAmount) -> Vec<Cell> {
    vec![t(format!("{} — {}", rows.code, rows.name)), Cell::Kobo(rows.amount_kobo)]
}

pub fn export_income_statement_accrual(header: &ExportHeader, stmt: &IncomeStatement) -> Result<Vec<u8>, String> {
    let columns = ["Line", "Amount"];
    let mut data = vec![vec![t("Revenue"), Cell::Kobo(0)]];
    data.extend(stmt.revenue.iter().map(account_amount_rows));
    data.push(vec![t("Total revenue"), Cell::Kobo(stmt.revenue_total_kobo)]);
    data.push(vec![t("Cost of goods sold"), Cell::Kobo(0)]);
    data.extend(stmt.cogs.iter().map(account_amount_rows));
    data.push(vec![t("Total COGS"), Cell::Kobo(stmt.cogs_total_kobo)]);
    data.push(vec![t("Gross profit"), Cell::Kobo(stmt.gross_profit_kobo)]);
    data.push(vec![t("Gross margin %"), Cell::Qty(stmt.gross_margin_bp as f64 / 100.0)]);
    data.push(vec![t("Operating expenses"), Cell::Kobo(0)]);
    data.extend(stmt.opex.iter().map(account_amount_rows));
    data.push(vec![t("Total operating expenses"), Cell::Kobo(stmt.opex_total_kobo)]);
    data.push(vec![t("Operating profit"), Cell::Kobo(stmt.operating_profit_kobo)]);
    data.push(vec![t("Non-operating (FX gain/loss)"), Cell::Kobo(stmt.non_operating_kobo)]);
    data.push(vec![t("Net profit"), Cell::Kobo(stmt.net_profit_kobo)]);
    build(header, &columns, &data)
}

pub fn export_income_statement_cash_basis(header: &ExportHeader, stmt: &CashBasisSummary) -> Result<Vec<u8>, String> {
    let columns = ["Line", "Amount"];
    let data = vec![
        vec![t(&stmt.caption), Cell::Kobo(0)],
        vec![t("Revenue (collected)"), Cell::Kobo(stmt.revenue_kobo)],
        vec![t("Expenses (paid)"), Cell::Kobo(stmt.expense_kobo)],
        vec![t("Net profit"), Cell::Kobo(stmt.net_profit_kobo)],
    ];
    build(header, &columns, &data)
}

pub fn export_balance_sheet(header: &ExportHeader, bs: &BalanceSheet) -> Result<Vec<u8>, String> {
    let columns = ["Line", "Amount"];
    let data = vec![
        vec![t("Cash and bank"), Cell::Kobo(bs.cash_and_bank_kobo)],
        vec![t("Receivables"), Cell::Kobo(bs.receivables_kobo)],
        vec![t("Inventory"), Cell::Kobo(bs.inventory_kobo)],
        vec![t("Fixed assets (net)"), Cell::Kobo(bs.fixed_assets_net_kobo)],
        vec![t("Other assets"), Cell::Kobo(bs.other_assets_kobo)],
        vec![t("Total assets"), Cell::Kobo(bs.total_assets_kobo)],
        vec![t("Current liabilities"), Cell::Kobo(bs.current_liabilities_kobo)],
        vec![t("Loans"), Cell::Kobo(bs.loans_kobo)],
        vec![t("Other liabilities"), Cell::Kobo(bs.other_liabilities_kobo)],
        vec![t("Total liabilities"), Cell::Kobo(bs.total_liabilities_kobo)],
        vec![t("Opening balance equity"), Cell::Kobo(bs.opening_balance_equity_kobo)],
        vec![t("Owner capital"), Cell::Kobo(bs.owner_capital_kobo)],
        vec![t("Drawings"), Cell::Kobo(bs.drawings_kobo)],
        vec![t("Retained earnings"), Cell::Kobo(bs.retained_earnings_kobo)],
        vec![t("Current year earnings"), Cell::Kobo(bs.current_year_earnings_kobo)],
        vec![t("Total equity"), Cell::Kobo(bs.total_equity_kobo)],
        vec![t("Ties (assets = liabilities + equity)"), t(if bs.ties { "Yes" } else { "No" })],
    ];
    build(header, &columns, &data)
}

pub fn export_cash_flow_statement(header: &ExportHeader, cf: &CashFlowStatement) -> Result<Vec<u8>, String> {
    let columns = ["Line", "Amount"];
    let data = vec![
        vec![t("Operating activities"), Cell::Kobo(cf.operating_kobo)],
        vec![t("Investing activities"), Cell::Kobo(cf.investing_kobo)],
        vec![t("Financing activities"), Cell::Kobo(cf.financing_kobo)],
        vec![t("Net change in cash"), Cell::Kobo(cf.net_change_kobo)],
        vec![t("Opening cash"), Cell::Kobo(cf.opening_cash_kobo)],
        vec![t("Closing cash"), Cell::Kobo(cf.closing_cash_kobo)],
        vec![t("Ties to the bank delta"), t(if cf.ties { "Yes" } else { "No" })],
    ];
    build(header, &columns, &data)
}

pub fn export_trial_balance(header: &ExportHeader, rows: &[TrialBalanceRow]) -> Result<Vec<u8>, String> {
    let columns = ["Code", "Account", "Class", "Debit", "Credit"];
    let data = rows
        .iter()
        .map(|r| vec![t(&r.code), t(&r.name), t(&r.class), Cell::Kobo(r.debit_kobo), Cell::Kobo(r.credit_kobo)])
        .collect::<Vec<_>>();
    build(header, &columns, &data)
}

pub fn export_general_ledger(header: &ExportHeader, gl: &GeneralLedger) -> Result<Vec<u8>, String> {
    let columns = ["Date", "Memo", "Contact", "Amount", "Running balance"];
    let mut data = vec![vec![
        t("Opening balance"), t(""), t(""), Cell::Kobo(0), Cell::Kobo(gl.opening_balance_kobo),
    ]];
    data.extend(gl.lines.iter().map(|l| {
        vec![
            Cell::Date(l.date.clone()), t(&l.memo), t(l.contact_name.clone().unwrap_or_default()),
            Cell::Kobo(l.amount_kobo), Cell::Kobo(l.running_balance_kobo),
        ]
    }));
    data.push(vec![t("Closing balance"), t(""), t(""), Cell::Kobo(0), Cell::Kobo(gl.closing_balance_kobo)]);
    build(header, &columns, &data)
}

pub fn export_vat_report(header: &ExportHeader, vr: &VatReport) -> Result<Vec<u8>, String> {
    let columns = ["Type", "Document", "Party", "TIN", "Net", "VAT"];
    let mut data: Vec<Vec<Cell>> = vr
        .output
        .iter()
        .map(|l| vec![t("Output"), t(&l.doc_number), t(&l.party_name), t(l.tin.clone().unwrap_or_default()), Cell::Kobo(l.net_kobo), Cell::Kobo(l.vat_kobo)])
        .collect();
    data.extend(vr.input.iter().map(|l| {
        vec![t("Input"), t(&l.doc_number), t(&l.party_name), t(l.tin.clone().unwrap_or_default()), Cell::Kobo(l.net_kobo), Cell::Kobo(l.vat_kobo)]
    }));
    data.push(vec![t("Total output VAT"), t(""), t(""), t(""), t(""), Cell::Kobo(vr.output_vat_kobo)]);
    data.push(vec![t("Total input VAT"), t(""), t(""), t(""), t(""), Cell::Kobo(vr.input_vat_kobo)]);
    data.push(vec![t("Net payable (this month)"), t(""), t(""), t(""), t(""), Cell::Kobo(vr.net_payable_kobo)]);
    data.push(vec![t("Credit brought forward"), t(""), t(""), t(""), t(""), Cell::Kobo(vr.credit_brought_forward_kobo)]);
    data.push(vec![t("Net due"), t(""), t(""), t(""), t(""), Cell::Kobo(vr.net_due_kobo)]);
    build(header, &columns, &data)
}

pub fn export_wht_remittance(header: &ExportHeader, rows: &[WhtRemittanceLine]) -> Result<Vec<u8>, String> {
    let columns = ["Payment date", "Supplier", "TIN", "Bill ref", "Base amount", "WHT withheld"];
    let data = rows
        .iter()
        .map(|r| {
            vec![
                Cell::Date(r.payment_date.clone()), t(&r.supplier_name), t(r.tin.clone().unwrap_or_default()),
                t(r.bill_ref.clone().unwrap_or_default()), Cell::Kobo(r.base_kobo), Cell::Kobo(r.wht_kobo),
            ]
        })
        .collect::<Vec<_>>();
    build(header, &columns, &data)
}

pub fn export_wht_credit(header: &ExportHeader, rows: &[WhtCreditLine]) -> Result<Vec<u8>, String> {
    let columns = ["Receipt date", "Customer", "TIN", "Base amount", "WHT withheld"];
    let data = rows
        .iter()
        .map(|r| {
            vec![
                Cell::Date(r.receipt_date.clone()), t(&r.customer_name), t(r.tin.clone().unwrap_or_default()),
                Cell::Kobo(r.base_kobo), Cell::Kobo(r.wht_kobo),
            ]
        })
        .collect::<Vec<_>>();
    build(header, &columns, &data)
}

pub fn export_contact_statement(header: &ExportHeader, cs: &ContactStatement) -> Result<Vec<u8>, String> {
    let columns = ["Date", "Description", "Debit", "Credit", "Running balance"];
    let mut data = vec![vec![t("Opening balance"), t(""), Cell::Kobo(0), Cell::Kobo(0), Cell::Kobo(cs.opening_balance_kobo)]];
    data.extend(cs.lines.iter().map(|l| {
        let desc = if l.voided { format!("{} (voided)", l.description) } else { l.description.clone() };
        vec![Cell::Date(l.date.clone()), t(desc), Cell::Kobo(l.debit_kobo), Cell::Kobo(l.credit_kobo), Cell::Kobo(l.running_balance_kobo)]
    }));
    data.push(vec![t("Closing balance"), t(""), Cell::Kobo(0), Cell::Kobo(0), Cell::Kobo(cs.closing_balance_kobo)]);
    build(header, &columns, &data)
}
